#!/usr/bin/env bash
# Generates test/all_lib_imports_test.dart, a test that imports every file
# under lib/ so that files no test touches still appear in lcov.info with
# zero covered lines (architecture.md §18.4). The file is git-ignored.
set -euo pipefail
cd "$(dirname "$0")/.."

package="$(sed -n 's/^name:[[:space:]]*//p' pubspec.yaml | head -1)"
if [ -z "$package" ]; then
  echo "gen_coverage_helper: could not read the package name from pubspec.yaml" >&2
  exit 1
fi

out="test/all_lib_imports_test.dart"
mkdir -p test
{
  echo "// GENERATED by tool/gen_coverage_helper.sh. Do not edit; do not commit."
  echo "// Imports every lib/ file so untested files count as zero coverage."
  echo "// ignore_for_file: unused_import, directives_ordering"
  echo
  find lib -name '*.dart' \
    ! -name '*.g.dart' ! -name '*.freezed.dart' ! -path 'lib/l10n/generated/*' \
    | sort \
    | sed -e "s|^lib/|import 'package:${package}/|" -e "s|\$|';|"
  echo
  echo "void main() {}"
} > "$out"
echo "wrote $out"
